name: .NET

on:
  push:
    branches: [ main ]
  #pull_request:
   #branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Show current file list
        run: ls

      - name: Restore dependencies - jyu.demo.rabbitmq.App
        run: dotnet restore ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.App/
      - name: Build jyu.demo.rabbitmq.App
        run: dotnet build ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.App --no-restore