name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Show current file list
        run: ls

      - name: Show jyu.demo.rabbitmq.App file lsit
        run: ls ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.App
      - name: Restore dependencies - jyu.demo.rabbitmq.App
        run: dotnet restore ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.App
      - name: Build jyu.demo.rabbitmq.App
        run: dotnet build ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.App --no-restore
  
      - name: Show jyu.demo.rabbitmq.Init file lsit
        run: ls ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.Init
      - name: Restore dependencies - jyu.demo.rabbitmq.Init
        run: dotnet restore ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.Init
      - name: Build jyu.demo.rabbitmq.Init
        run: dotnet build ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.Init --no-restore

      - name: Show jyu.demo.rabbitmq.Utilities file lsit
        run: ls ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.Utilities
      - name: Restore dependencies - jyu.demo.rabbitmq.Utilities
        run: dotnet restore ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.Utilities
      - name: Build jyu.demo.rabbitmq.Utilities
        run: dotnet build ./src/jyu.demo.rabbitmq/jyu.demo.rabbitmq.Utilities --no-restore